spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: 8188121
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
logging:
  file:
    name: logs/student_management_service.log
  level:
    az.spring.studentmanagementservice: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR